[build-system]
requires = ["setuptools>64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "stanalyzer"
version = "0.1.0"

[tool.setuptools.package-dir]
stanalyzer = "src"
