[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "stanalyzer"
dynamic = ["version"]

[project.scripts]
stanalyzer = "stanalyzer.cli.stanalyzer:main"
sta-server = "stanalyzer.cli.stanalyzer:run_server"

[tool.setuptools_scm]
