[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "stanalyzer"
dynamic = ["version"]

[project.scripts]
stanalyzer = "stanalyzer.cli.stanalyzer:main"
sta-server = "stanalyzer.cli.stanalyzer:run_server"

[tool.setuptools_scm]

[tool.mypy]
# https://docs.pydantic.dev/latest/integrations/mypy/
plugins = ["pydantic.mypy", "numpy.typing.mypy_plugin"]
python_version = "3.10"  # may raise to 3.12 later

# see below for mypy configuration settings, if using mypy type checking:
#   https://mypy.readthedocs.io/en/stable/config_file.html
#   https://mypy.readthedocs.io/en/stable/error_codes.html
check_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
strict_equality = true
strict_bytes = true
show_error_context = true
show_column_numbers = true
show_error_code_links = true
pretty = true

disable_error_code = "import-untyped"  # generated by MDAnalysis and scipy

# settings intended for future updates
#disallow_subclassing_any = true
#disallow_untyped_calls = true
#disallow_untyped_defs = true
#disallow_untyped_decorators = true

# settings that might conflict with stdlib and other dependencies
#disallow any_decorated = true
#disallow_any_explicit = true
#disallow_any_expression = true
#disallow_any_generics = true
