package:
  name: stanalyzer
  version: 0.1.0

source:
  git_url: https://github.com/nk53/stanalyzer.git
  git_rev: sta

build:
  number: 1
  entry_points:
    - stanalyzer = stanalyzer.cli.stanalyzer:main
    - sta-server = stanalyzer.cli.stanalyzer:run_server

about:
  home: https://github.com/nk53/stanalyzer
  license: MIT
  license_file: LICENSE
  license_url: https://github.com/nk53/stanalyzer/blob/sta-dev/LICENSE
  summary: Command-line and web interface for common simulation trajectory analysis
  description: |
    An extensible framework for analyzing molecular dynamics simulation trajectories. Several analysis programs are provided, and sophisticated users can add their own analysis types.
  dev_url: https://github.com/nk53/stanalyzer
  doc_url: https://github.com/nk53/stanalyzer/blob/sta-dev/README.md
  doc_source_url: https://github.com/nk53/stanalyzer/blob/sta-dev/README.md

test:
  imports:
    - stanalyzer
    - stanalyzer.cli.stanalyzer

requirements:
  build:
    - python=3.10
    - setuptools>64
    - setuptools_scm>=8
  run:
    - python=3.10
    - hole2=2.3
    - freesasa=2.2
    - fastapi=0.115
    - uvicorn=0.32
    - jinja2=3.1
    - sqlmodel>=0.0.22
    - mdanalysis=2.7
    - email-validator=2.2
    - python-multipart>=0.0.17
    - pyyaml=6.0
    - paramiko=3.5
    - fabric=3.2
    - invoke=2.2
    - pylsp-mypy=0.6
    - sphinx=8.1
    - sphinx-js=3.2
